# Generated by Django 4.2 on 2023-05-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(default='users/default-user.png', null=True, upload_to='users/'),
        ),
    ]
