# Generated by Django 4.2 on 2023-05-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
