# Generated by Django 4.2 on 2023-04-17 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0002_alter_customuser_birth_data_alter_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='barber',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.qualifications'),
        ),
    ]
