# Generated by Django 4.2 on 2023-05-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_barber_barbershop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='users/'),
        ),
    ]
