# Generated by Django 4.2 on 2023-06-15 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_services_duration_hours'),
        ('salon', '0005_barbershop_rating'),
        ('users', '0005_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='barbershop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salon.barbershop'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.qualifications'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
