# Generated by Django 4.2 on 2023-05-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='users/<django.db.models.query_utils.DeferredAttribute object at 0x000001FA744DA020>'),
        ),
    ]
