# Generated by Django 4.2 on 2023-04-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_city_barbershop_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salon.city'),
        ),
    ]
