# Generated by Django 4.2 on 2023-05-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_barbershop_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
