# Generated by Django 4.2 on 2023-05-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_alter_barbershop_full_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
