# Generated by Django 4.2 on 2023-06-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_barbershop_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershop',
            name='full_description',
            field=models.CharField(max_length=1024),
        ),
    ]
