# Generated by Django 4.2 on 2023-05-08 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.barber'),
        ),
        migrations.AddField(
            model_name='booking',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.barbershop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceprice'),
        ),
    ]
