# Generated by Django 4.2 on 2023-06-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='duration_hours',
        ),
    ]
