# Generated by Django 4.2 on 2023-04-18 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_workingtime_remove_booking_time_booking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appointment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='appointment_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.workingtime'),
        ),
    ]
