# Generated by Django 4.2 on 2023-04-20 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
        ('users', '0004_barber_barbershop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0004_booking_appointment_date_booking_appointment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.barber')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.barbershop')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
