# Generated by Django 4.2 on 2023-04-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
