# Generated by Django 4.2 on 2023-04-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_delete_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='hour',
            field=models.TimeField(),
        ),
    ]
