# Generated by Django 4.2 on 2023-04-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_workingtime_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='hour',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
