# Generated by Django 4.2 on 2023-05-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_booking_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
