# Generated by Django 4.2 on 2023-05-08 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='services.booking'),
        ),
    ]
