# Generated by Django 4.2 on 2023-05-01 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_booking_creation_time'),
        ('reviews', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='services.booking'),
        ),
    ]
